spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update # ?? validate ?? ???? db? ??? ?? ? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!
